# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e3979caaa863c6884354071afa6a90529588f813ab85880a15672f4edd1e649003e8ca60081849e12acb9a125352004e6b2534ba491bbe9fa69850effc006f

test:
  secret_key_base: 72d79ac30d31892bb8f388f830572c80b78703152c183b8ad31444348a5aad677e15f5ad19b9b5140ad90ce8cea99d326cfbcea7cdbef3a6dd82a901c585a09f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
